"""Regenerate pairwise_tasks.py from MyMain_SL.ipynb.

Parses every SVM pairwise-decoding cell (the `# (N) exp_names_list_*` blocks that
use svm.LinearSVC) and extracts its `data_root_list` / `exp_name_list` literals.

    python pairwise_svm/gen_pairwise_tasks.py

Run this after editing the task lists in the notebook.
"""
import ast
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
NOTEBOOK = os.path.join(HERE, os.pardir, "MyMain_SL.ipynb")
OUT = os.path.join(HERE, "pairwise_tasks.py")


def strip_comments(s):
    out = []
    for line in s.splitlines():
        q = None
        res = []
        for ch in line:
            if q:
                res.append(ch)
                if ch == q:
                    q = None
            elif ch in "'\"":
                q = ch
                res.append(ch)
            elif ch == "#":
                break
            else:
                res.append(ch)
        out.append("".join(res))
    return "\n".join(out)


def extract_list(src, name):
    src = strip_comments(src)
    m = re.search(rf"^\s*{name}\s*=\s*(\[)", src, re.M)
    if not m:
        return None
    i = m.start(1)
    depth = 0
    instr = None
    for j in range(i, len(src)):
        ch = src[j]
        if instr:
            if ch == instr:
                instr = None
            continue
        if ch in "'\"":
            instr = ch
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                try:
                    return ast.literal_eval(src[i:j + 1])
                except Exception:
                    return None
    return None


def main():
    nb = json.load(io.open(NOTEBOOK, encoding="utf-8"))
    cells = ["".join(c["source"]) for c in nb["cells"] if c["cell_type"] == "code"]

    tasks = {}
    for src in cells:
        m = re.search(r"#\s*\((\d+)\)\s*(exp_names_list\S*)", src)
        if not m or "LinearSVC" not in src:
            continue
        key = m.group(2).rstrip("'\"")[len("exp_names_list_"):]
        drl = extract_list(src, "data_root_list")
        enl = extract_list(src, "exp_name_list")
        if not isinstance(drl, list) or not isinstance(enl, list) or not enl:
            print(f"  skip ({m.group(1)}) {key}: could not parse")
            continue
        if len(drl) == 1 and len(enl) > 1:
            drl = drl * len(enl)
        drl = drl[:len(enl)] + [drl[-1]] * max(0, len(enl) - len(drl))
        tasks[key] = {
            "notebook_id": int(m.group(1)),
            "source_name": m.group(2).rstrip("'\""),
            "data_root_list": drl,
            "exp_name_list": [list(p) for p in enl],
        }
        print(f"  ({m.group(1)}) {key}: {len(enl)} pairs")

    lines = [
        '"""Auto-generated by gen_pairwise_tasks.py from MyMain_SL.ipynb. Do not edit by hand.',
        "",
        "One entry per SVM pairwise-decoding task. For pair i, the two feature files are",
        "    <data_root_list[i]>/<exp_name_list[i][k]>_<model><filename_postfix>.pth",
        '"""',
        "",
        "TASKS = {",
    ]
    for key, v in tasks.items():
        roots = v["data_root_list"]
        lines.append(f"    {key!r}: {{")
        lines.append(f"        \"notebook_id\": {v['notebook_id']},")
        lines.append(f"        \"source_name\": {v['source_name']!r},")
        if len(set(roots)) == 1:
            lines.append(f"        \"data_root\": {roots[0]!r},")
        else:
            lines.append("        \"data_root_list\": [")
            for r in roots:
                lines.append(f"            {r!r},")
            lines.append("        ],")
        lines.append("        \"exp_name_list\": [")
        for a, b in v["exp_name_list"]:
            lines.append(f"            [{a!r}, {b!r}],")
        lines.append("        ],")
        lines.append("    },")
    lines.append("}")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nwrote {OUT}  ({len(tasks)} tasks)")


if __name__ == "__main__":
    main()
